services:
  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root@123"
      POSTGRES_DB: "finance_db"
    ports:
      - "5432:5432"
    volumes:
      - ./db-scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    command: [
      "postgres",
      "-c", "wal_level=logical",
      "-c", "max_replication_slots=10",
      "-c", "max_wal_senders=10"
    ]
